### ISSUE TITLE
Hostgator SMTP is sending, but never delivered

### ISSUE THREAD

**Issue by ivanrios** [nodemailer/nodemailer#603]
Include the following information with your issue:

Node V 4.2.2
Nodemailer V 1.3.1

The server response 250 OK, I have the messageId but the email is not being delivered, Hostgator saids they can see the email marked as sent on their backend but I don´t have it on my inbox, any clue? we have hundreds of accounts working (gmail, hotmail, smtp) , since 2 weeks ago accounts with that hosting service are not working, any clue?

**Comment by andris9** [comment]
If Nodemailer gets a 2xx response from the SMTP server then everything worked correctly. This doesn't mean yet that the message would be actually delivered but what happens afterwards is out if control for Nodemailer. There's absolutely nothing Nodemailer can do once the message is accepted by the SMTP server

**Comment by rafaelgondim** [comment]
I'm having the same problem. Emails from sent via web client are delivered, but emails sent by nodemailer don't arrive, and I'm getting 250 OK either.
@ivanrios Did you find a solution, I' know  it's a while, but I have no clue.

**Comment by alobaidizt** [comment]
I get 250 Ok too and it's not delivered. I'm using Bluehost SMTP server settings. Can anyone comment?

**Comment by ar124official2019** [comment]
Facing same issue with Hostgator hosted email.

**Comment by rafaelgondim** [comment]
Hostgator will reject your commands if you send the HELLO message with the IP 127.0.0.1

**Comment by ar124official2019** [comment]
> Hostgator will reject your commands if you send the HELLO message with the IP 127.0.0.1

It's not a case - I've deployed the product to some server, still now working.

**Comment by BrunoPierca** [comment]
> > Hostgator will reject your commands if you send the HELLO message with the IP 127.0.0.1
> 
> It's not a case - I've deployed the product to some server, still now working.

Could you fix this issue? I just tried deploying it but mine is still not working either

**Comment by captaincrazybro** [comment]
Btw, if anyone is still looking for a solution to this issue, I fixed this by assigning the `name` property when creating the transport to something other than the default.

**Comment by apoorv-1310** [comment]
> Btw, if anyone is still looking for a solution to this issue, I fixed this by assigning the `name` property when creating the transport to something other than the default.

can you share the code snippet ?

**Comment by rafaelgondim** [comment]
> > Btw, if anyone is still looking for a solution to this issue, I fixed this by assigning the `name` property when creating the transport to something other than the default.
> 
> can you share the code snippet ?

`
const transporter = nodemailer.createTransport({
            host: usuario.smtp.host,
            port: usuario.smtp.port,
            //Isso enche o log e faz a rotação, fazendo com que logs mais relevantes sejam perdidos
            // logger: true,
            // debug: true,
            auth: {
                user: ...,
                pass: ...
            },
            tls: {
                rejectUnauthorized: false // Ignora certificados invalidos
            },
            connectionTimeout: 60000,
            socketTimeout: 90000,
            name: os.hostname() || 'some-name',
            localAddress: ipAddToUse
        });
`

**Comment by captaincrazybro** [comment]
This is the config that I am using:
```javascript
{
  host: process.env.SMTP_SERVER ?? '',
  port: port,
  secure: port == 465,
  name: process.env.SMTP_NAME ?? '',
  auth: {
    user: process.env.SMTP_USERNAME ?? '',
    pass: process.env.SMTP_PASSWORD ?? '',
  },
}
```
I'm using a series of environment variables for my values.
According to the `nodemailer` documentation, the `name` property is the hostname of the client and defaults to the hostname of the machine, which would typically be the name of the OS. I figure that HostGator has some rules in place that block email requests using certain hostnames, particularly if they have the name of some OS, I'm guessing.

**Comment by apoorv-1310** [comment]
i tried same but i am not getting mail in gmail
even though the response is 200 OK

```
this.NM = nodemailer.createTransport(smtpTransport({
			host: "",
            port: 465,
            //Isso enche o log e faz a rotação, fazendo com que logs mais relevantes sejam perdidos
            logger: true,
			debug: true,
			secure: true,
            auth: {
                user:"",
                pass: ""
            },
            tls: {
                rejectUnauthorized: false // Ignora certificados invalidos
            },
            connectionTimeout: 60000,
            socketTimeout: 90000,
            name: '',
		}));
		
```
		
		response
		
```
response {
  accepted: [ 'apoorv.mittal92@gmail.com' ],
  rejected: [],
  response: '250 OK id=1sbh8U-001eLv-08',
  envelope: { from: 'noreply@ampious.in', to: [ 'apoorv.mittal92@gmail.com' ] },
  messageId: '67721a52-b91c-9752-08e1-b731eb50fd12@ampious.in'
}
```

**Comment by captaincrazybro** [comment]
Sorry, the name shouldn't be empty. I provide those default empty values, but only because I want to prevent the entire program from failing at that point.

**Comment by janduy** [comment]
> > > Btw, if anyone is still looking for a solution to this issue, I fixed this by assigning the `name` property when creating the transport to something other than the default.
> > 
> > 
> > can you share the code snippet ?
> 
> ```
> const transporter = nodemailer.createTransport({
>             host: usuario.smtp.host,
>             port: usuario.smtp.port,
>             //Isso enche o log e faz a rotação, fazendo com que logs mais relevantes sejam perdidos
>             // logger: true,
>             // debug: true,
>             auth: {
>                 user: ...,
>                 pass: ...
>             },
>             tls: {
>                 rejectUnauthorized: false // Ignora certificados invalidos
>             },
>             connectionTimeout: 60000,
>             socketTimeout: 90000,
>             name: os.hostname() || 'some-name',
>             localAddress: ipAddToUse
>         });
> ```

Hello, thank you for sharing the code, solved for my case.
